/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7fbf0",
        "surface-dim": "#d7dbd2",
        "surface-bright": "#f7fbf0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5eb",
        "surface-container": "#ebefe5",
        "surface-container-high": "#e5eadf",
        "surface-container-highest": "#e0e4da",
        "on-surface": "#181d17",
        "on-surface-variant": "#40493d",
        "inverse-surface": "#2d322b",
        "inverse-on-surface": "#eef2e8",
        outline: "#707a6c",
        "outline-variant": "#bfcaba",
        "surface-tint": "#1b6d24",
        primary: "#0d631b",
        "on-primary": "#ffffff",
        "primary-container": "#2e7d32",
        "on-primary-container": "#cbffc2",
        "inverse-primary": "#88d982",
        secondary: "#8f4e00",
        "on-secondary": "#ffffff",
        "secondary-container": "#ff8f00",
        "on-secondary-container": "#623400",
        tertiary: "#006156",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#097c6e",
        "on-tertiary-container": "#bdfff1",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005312",
        "secondary-fixed": "#ffdcc2",
        "secondary-fixed-dim": "#ffb77a",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-fixed-variant": "#6d3a00",
        "tertiary-fixed": "#97f3e2",
        "tertiary-fixed-dim": "#7ad7c6",
        "on-tertiary-fixed": "#00201b",
        "on-tertiary-fixed-variant": "#005047",
        background: "#f7fbf0",
        "on-background": "#181d17",
        "surface-variant": "#e0e4da",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 20px rgba(0, 0, 0, 0.04)",
        "card-sm": "0 4px 20px rgba(0, 0, 0, 0.02)",
        lift: "0 8px 24px rgba(0, 0, 0, 0.06)",
      },
      maxWidth: {
        content: "1280px",
      },
    },
  },
  plugins: [],
};
